---
title: "Fazendo gráficos com os dados"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{graficos}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
 # fig.path = "man/figures/README-",
  out.width = "100%"
)
```

```{r setup}
library(mananciais)
```



# Todos os anos

```{r ggplot, dpi = 600}
library(ggplot2)
mananciais %>%
  ggplot() +
  geom_line(aes(x = data, y = volume_porcentagem)) +
  scale_y_continuous(breaks = c(-25, 0, 25, 50, 75, 100)) +
  facet_wrap(~ sistema, ncol = 2) +
  theme_bw() +
  labs(x = "Ano", y = "Volume armazenado (%)")
```


## Apenas ano 2020

```{r ggplot2, dpi = 600}
mananciais %>%
  dplyr::mutate(ano = lubridate::year(data)) %>%
  dplyr::filter(ano == 2020) %>%
  ggplot() +
  geom_line(aes(x = data, y = volume_porcentagem)) +
  scale_y_continuous(breaks = c(-25, 0, 25, 50, 75, 100)) +
  facet_wrap(~ sistema, ncol = 2) +
  theme_bw() +
  labs(x = "Meses", y = "Volume armazenado (%)")
```
